### ISSUE TITLE
Team page fails to credit Bitcoin Core's most senior developers

### ISSUE THREAD

**Issue by homerjthompson** [bitcoin-core/bitcoincore.org#161]
The team page fails to list @jgarzik and @gavinandresen, these are Bitcoin Core's most senior contributors. They rank #1 and #2 on the Bitcoin project and are two of the only five people with the private keys needed to make changes to Bitcoin. Gavin is Bitcoin's chief scientist.

It is hard to believe they were left off by mistake.

**Comment by homerjthompson** [comment]
https://bitcoincore.org/en/team/

**Comment by jameshilliard** [comment]
1. The team page is not a credits page, those are found in the individual release notes for each Bitcoin Core release.
2. The team page shows the regular day to day contributors who regularly contribute a significant amount of time to the Bitcoin Core project.
3. Gavin is Chief Scientist of the Bitcoin Foundation, a private organisation (which has no money and has a bad reputation), he is not Chief Scientist of "Bitcoin".
4. Bitcoin Core is a discrete software project, it is not "Bitcoin".
5. Bitcoin consensus rules are decided by users of Bitcoin according to which software they choose to run. You are mistaken, there are no "private keys" that are capable of changing the Bitcoin protocol. Bitcoin Core is software which users may or may not choose to run. The maintainers of the project are accurately reflected on the [team page](https://bitcoincore.org/en/team/). The way the Bitcoin Core project operates is clearly explained on the Contributing page at https://bitcoincore.org/en/faq/contributing-code/. Neither Gavin or Jeff have permission to merge changes to the Bitcoin Core project.
6. Gavin handed over his maintainer position to Wladimir over two years ago and clearly moved onto other projects as can be clearly seen from his lack of activity in the Bitcoin Core project. I am not sure why you would believe he is still part of the Bitcoin Core project, especially after acting with so much hostility towards the project and its contributors. The same can be said of Jeff.
7. I don't know where you are getting *#*1 and *#*2 from but by current metrics the top contributors in terms of [lines of code added](https://github.com/bitcoin/bitcoin/graphs/contributors?from=2015-04-21&to=2016-04-21&type=a) over the last 12 months would be Wladimir J. van der Laan, Pieter Wuille and Jonas Schnelli or Wladimir J. van der Laan, Jonas Schnelli and Marco Falke in terms of [commit count](https://github.com/bitcoin/bitcoin/graphs/contributors?from=2015-04-21&to=2016-04-21&type=c), anyway lines of code and commit count are both poor metrics because they don’t reflect other important and time consuming tasks like peer review, code review, testing and so on.

**Comment by laanwj** [comment]
They are no longer involved with day-to-day business of the project. You could say they have retired from the Bitcoin Core project quite a long time ago. You could figure out around when by looking at discussion on the github repository, or looking at commit counts.

The team page is not about 'giving credit'. Not everyone who contributed to the code is listed there, as that would be a huge list. For that see the complete list under each release notes: https://github.com/bitcoin/bitcoin/blob/v0.12.0/doc/release-notes.md#credits
