### ISSUE TITLE
Update the team-page

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/bitcoincore.org#470]
The team page should be updated (add/remove some devs).

I propose we add...
* @morcos
* @jnewbery 
* @ryanofsky
* @promag
* @achow101 
(more?)

Maybe remove...
@pstratem (seems no longer active)

**Comment by MarcoFalke** [comment]
Ack

**Comment by promag** [comment]
ACK I guess :P

**Comment by jnewbery** [comment]
I'm personally not a fan of the team page, and would prefer to see it removed. It reinforces the mistaken belief that 'Bitcoin Core' is a group/organization.

I think it's ok (although not necessary) to have the maintainers listed, since they have a functional role. I don't think it's a good idea to include 'contributors'. There's no difference between me and any random passing contributor - we each have the same rights to open PRs and comment on open PRs.

I'd prefer to see the **contributors** section of the team page reduced to something like:

> Everyone is free to propose code changes and to test, review and comment on open Pull Requests. Anyone who contributes code, review, test, translation or documentation to the Bitcoin Core project is considered a contributor. The release notes for each Bitcoin Core software release contain a credits section to recognize all those who have contributed to the project over the previous release cycle.

(If we do decide to keep the team contributors section, no need to include me. Thanks!)

**Comment by MarcoFalke** [comment]
I think the motivation for the team page was to convey that there are many who contributed commits and then list the ones that had the most commits in the previous releases. Probably to give them additional credit (as not everyone digs up the release notes).

Though, over the months, no one seems to update that page and it might convey a false sense of "closed group membership".
I think adding the paragraph that @jnewbery suggested and linking to https://github.com/bitcoin/bitcoin/graphs/contributors?from=${12_MONTHS_AGO}&type=c gives all of the recent contributors some additional credit beside the release notes without having to update the page or create a false impression of a fixed group.

**Comment by jnewbery** [comment]
> I think adding the paragraph that @jnewbery suggested and linking to https://github.com/bitcoin/bitcoin/graphs/contributors?from=${12_MONTHS_AGO}&type=c gives all of the recent contributors some additional credit

Yes, I think that's fine, although wording should be careful - number of commits is not a good metric for how much an individual has contributed (it doesn't capture maintenance tasks, review, test, documentation, etc)

**Comment by morcos** [comment]
I asked to be removed from this page when I had concerns about exactly what being part of Bitcoin Core represented.  I think there were just a few growing pains in finding a bit of voice as a project.  I'm generally happy with the way the project does PR now, which is almost entirely limited to factual information about releases or explaining features.

So in short, if we decide to keep this page, I'm happy to be readded, but I can also see @jnewbery's point of view.

**Comment by TheBlueMatt** [comment]
I'd tend to echo @morcos' comments, but agree that I can see a strong argument for not having a team page due to the issues in getting it right and the strong potential for misinterpretation.

**Comment by harding** [comment]
I'm not fond of the team page (but not opposed to it) for the reason stated earlier that it may give the impression that there's a closed set of contributors.

On the other hand, I do like the idea of emphasizing that Bitcoin Core does have an active contributor community.  Maybe an alternative and more generally-agreeable way to do that would be to have a *Thank You* page where we thank the people who have contributed to Bitcoin Core.  One hopefully-easy way to do that would be to YAMLize the Credits section @laanwj  puts at the end of each releases notes and use that data to generate a list linking contributor names to the releases they contributed.  Since Wladimir is already doing that work, maintaining that would cost basically nothing extra---making it less likely to fall out of date. 

For example, it might look something like this:

> ## Alice Aardvark
> 
> - 0.15.1
> - 0.15.0
> - 0.13.0
> - 0.10.0
>
> ## Bob Babbage 
>
> - 0.13.1
> - 0.12.0 
>
> ...

If there's interest, I can work on that.

**Comment by achow101** [comment]
I think we should just have the team page show the people publicly listed on the Bitcoin github organization as those are all of the frequent contributors.

**Comment by harding** [comment]
The list of contributors was removed in #519 after further discussion similar to this issue.  Closing this, but I'll be happy to reopen if anyone wants to follow up on some of the ideas discussed here.
