### ISSUE TITLE
Replace font

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/bitcoincore.org#54]
Is it just me or does the font look odd? I was thinking about proposing 2 or 3 different fonts and then vote which one looks best?

**Comment by jonasschnelli** [comment]
I agree, the font could be better.
But – speaking as webdev/designer now – changing the CI/CD (layout) after release the website should be combined and done as a complete re-design IMO. Just changing the font (even if its "better"/more acceptable) can confuse visitors.

But we could look for a better font and start working on a redesign (together with other things).

**Comment by btcdrak** [comment]
Until we get the functionality stuff done, design is likely to get in the way. There is a channel on slack called #website if you'd like to discuss there.

**Comment by neurohax** [comment]
I'd like to help with design, I will join the slack.  The issue is there is a variety of different fonts, the width of the primary font does not match the bitcoin logo, and times new roman (serif) is mixed with default fonts' san serif.  A quick and simple fix would be to use Helvetica Neue, Helvetica, Arial fallback for all fonts.  This does not really constitute a redesign and would not get in the way- I could handle this and PR if you are open to
