### ISSUE TITLE
dead links for gpg-keys on the announcements page (again)

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoin-core/bitcoincore.org#543]
It seems https://github.com/bitcoin-core/bitcoincore.org/issues/170 has reemerged.

The links on https://bitcoincore.org/en/list/announcements/join/ to the three listed keys all respond with 404. For example https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-keys/laanwj-key.pgp

**Comment by MarcoFalke** [comment]
Indeed. We might want to link to some actual keyserver and not a GitHub repo that only used to have the outdated keys.

**Comment by jonasschnelli** [comment]
Be aware that linking to the git repository and actually taking keys from the soucres seems more secure then consulting a random keyserver. Our sources can be verified through git signatures as well as though the gitian signatures.

A key-id in the sources may be enough, though, if you have to verify multiple layers, the tendency will be to skip one of those layers...

**Comment by harding** [comment]
Shouldn't we just put the keys on this website, like already done for https://bitcoincore.org/keys/laanwj-releases.asc linked from the Download page?

I do like the idea of listing the key fingerprints alongside the key links, although I suppose that could encourage people not to look to outside verification.  That's probably not an issue since an attacker serving a bad version of the page could already do that.

I'm happy to PR the change if we agree on what to do.

**Comment by kallerosenbaum** [comment]
Oh, I just added an issue, https://github.com/bitcoin-core/bitcoincore.org/issues/544, for displaying fingerprints on the downloads page. Didn't see your post here @harding .
