### ISSUE TITLE
Display pubkey fingerprint on downloads page

### ISSUE THREAD

**Issue by kallerosenbaum** [bitcoin-core/bitcoincore.org#544]
I think it would be good to display, on the downloads page, the fingerprint of the pubkey used to sign SHA256SUMS.asc.

This is what a completely new user has to do today:

1. Download Bitcoin Core and SHA256SUMS.asc
2. Download the key manually from the download page
3. Import the key into gpg
4. Get the fingerprint from gpg
5. verify the fingerprint with other sources like friends.
6. sign the key as trusted

Wouldn't it be easier for users if they could

1. Download Bitcoin Core and SHA256SUMS.asc
2. Copy the fingerprint from that same download page
3. verify the fingerprint with other sources like friends.
4. gpg --recv-keys \<fingerprint>
5. sign the key as trusted

**Comment by harding** [comment]
What do y'all think about putting the verification instructions directly on the download page.  (Some quick sample text shown below.)

![2018-04-26-14_26_34_855927401](https://user-images.githubusercontent.com/61096/39324647-06144e42-495e-11e8-864d-e44da1bea4ba.png)

Also, if we proceed, can anyone verify for me whether or not gpg is installed by default on MacOS?

**Comment by laanwj** [comment]
@harding very good idea!

**Comment by kallerosenbaum** [comment]
Sounds good.

But I've heard people saying that putting up verification instructions is decreasing security, because people may follow them blindly without knowing what they're doing. This would give a false sense of security. Maybe add something about not following instructions blindly :-) Another reason to be careful with instructions is that they can be hacked.

Are these concerns valid?

**Comment by harding** [comment]
I think it would definitely be a good idea to link to a nice off-site GPG guide that goes into the details of verification for anyone who wants to understand what they're doing; I'll do that when I create a PR for this.  That said, I think there's still benefit to a simple list of verification instructions: any attacker who changes them runs the risk of showing them to a PGP-aware user who might notice the deviation from acceptable practices or known key fingerprints and raise an alarm.

The risk of hacking for instructions on the bottom of the page seems no greater to me than the risk of hacking other parts of the page, especially the links to the binaries.  When I create the PR, I'll separate the URLs and the fingerprint from the readable text so that translation files can't alter them without doing something that looks weird, but security of the website content will still depend on the fundamental server security, peer review of PRs, and `verify-commits.sh`.
