### ISSUE TITLE
Hidden service for bitcoincore.org

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/bitcoincore.org#568]
There have been requests for bitcoincore.org on a hidden service. This could be useful for circumventing censorship. There's the torrent/magnet URI for downloading the binaries without access to the site, however this doesn't give access to any of the documentation hosted on the site.

Also, an hidden service would give an alternative (direct) trust path that doesn't rely on certificate authorities or DNS infrastructure.

**Comment by harding** [comment]
Strong concept ACK.

My current understanding is that the actual server is in colocated hosting with at least one VPS being used as a sacrificial proxy to defend against DoS attacks.  I think that means the goal can be accomplished three ways:

1. Setup the Tor HS directly on the server.  I've heard Tor HSes don't need protection against bandwidth-exhaustion DoS attacks because of Tor's low throughput, although maybe someone more knowledgeable should confirm that before a service is set up.

2. Setup the Tor HS on a proxy server, that way even if something goes wrong, it's still an easy sacrifice.  This does create a trust problem where compromise of the proxy leads to compromise of the HS's key.

3. Setup the Tor HS on a completely separate server that mirrors the site.  This ought to be easy to do---just copy over the build script for the site and write a short script to copy over the /bin directory from the DNS-based site after verifying the checksums/PGP sigs.  This has the same trust problem as the above option.

Option 3 can be done by any trusted person; option 1 has to be done by someone with current server access; option 2 can be done either way.

If it's true that Tor HSes don't require DoS protection and there are no other concerns I'm unaware of, then I think I prefer option 1 most of all.

**Comment by TheBlueMatt** [comment]
I'd rather run it on a separate server, but I'd be generally OK with running it in the same rack/uplink as the physical servers. Not sure if that's legit DoS-wise, but from a security perspective, if you're not getting the SSL it'd suck to use one of the mostly-untrusted VMs or something similar to terminate the Tor session.

**Comment by TheBlueMatt** [comment]
6hasakffvppilxgehrswmffqurlcjjjhd76jgvaqmsg6ul25s7t3rzyd.onion

**Comment by Sjors** [comment]
Light testing suggests it works like a charm. Do we want a vanity address?

**Comment by laanwj** [comment]
> 6hasakffvppilxgehrswmffqurlcjjjhd76jgvaqmsg6ul25s7t3rzyd.onion

Works for me.
We should probably announce it somewhere (maybe on the site itself).

**Comment by jonatack** [comment]
Just learned about this from @laanwj's announcement on the fediverse. Thanks @TheBlueMatt!

**Comment by laanwj** [comment]
> Do we want a vanity address?

I personally think no: onion addresses are not meaningful names, and if people get used to that "oh it starts with bitcoincore it must be ok" that kind of defeats the purpose
also there's a risk in exposing the private key to a GPU cluster or cloud or whatever it takes to grind these things

**Comment by harding** [comment]
Resolved via #691
