### ISSUE TITLE
Add SHA256SUMS.asc to release page

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/bitcoincore.org#598]
I suggest adding <pre>the contents of SHA256SUMS.asc</pre> to each release page. In case some binaries disappear like today`*`, or the site goes down, this information would be easier to retrieve, e.g. on Github, the Way Back Machine or Google cache. The binaries themselves can then be obtained from any source as long as you check the signatures.

`*` = they were moved to a different path due to the CVE issue

**Comment by harding** [comment]
The SHA256SUMS.asc is a convenience file for people doing single-source binary verification.  For archive purposes, I think the canonical archive should be https://github.com/bitcoin-core/gitian.sigs

In any case, I slightly oppose adding more dynamic information to the release files.  It's already a moderate pain to prepare them more than a day or two in advance of a release and then keep them in sync with what's going on during the RC cycle, and adding even more dynamic information to them would make that even more work.  If there's a compelling advantage to adding more information, it'll have my support, but otherwise, I'd prefer we try to keep the number of release steps involving this website minimal.

**Comment by Sjors** [comment]
The gitian.sigs repo is difficult to interpret because it contains builds from individual contributors. I also think it's not very well cached by Google and WBM, e.g. my signatures from a month ago [aren't there](https://web.archive.org/web/*/https://github.com/bitcoin-core/gitian.sigs/blob/master/0.16.2-linux/sjors/bitcoin-linux-0.16-build.assert). It's unlikely anyone outside a small number of core devs keep a recent copy of that repo.

**Comment by harding** [comment]
I agree it's harder to interpret than the shasums included in the release directories, but your OP describes a situation where people are digging through old release notes on a third-party site to find checksums, verifying signatures on those checksums, and then looking for files somewhere on the web that match those checksums.  I'd be surprised to discover a single user doing that, much less a significant enough number of users to justify adding additional burden to the release process of adding the checksums and having each PR reviewer verify them.

If there actually are users who need that information, I think the Gitian signatures repository is quite sufficient to satisfy them, so I think this issue should be closed unless there's some more compelling reason to include the contents of the signed release checksums file in the rendered-to-HTML release notes.

**Comment by luke-jr** [comment]
I agree with @harding. If anything, we should be discouraging use of `SHA256SUMS`.

If the gitian.sigs repo is too difficult, let's make it easier.

**Comment by Sjors** [comment]
> I'd be surprised to discover a single user doing that

I'm not sure what people would do it bitcoin-core.org is taken offline. My guess is that people start spreading ad hoc download and torrent links, some of which might contain that ASC file. Redundancy would help in such a scenario.

Anyway, turns out its trivial to tell the internet archive to save these ASC files, e.g. I just did it for https://web.archive.org/web/*/https://bitcoincore.org/bin/bitcoin-core-0.16.3/SHA256SUMS.asc

`gitian.sigs` could be made easier to use by adding `/releases/v0.16.3/SHA256SUMS.asc`. Alternatively those could go into the bitcoin repo itself, which is much more widespread.
