### ISSUE TITLE
Missing binaries ?

### ISSUE THREAD

**Issue by ocZio** [bitcoin-core/bitcoincore.org#605]
https://bitcoincore.org/bin/

Where are all the previous binaries ? 0.14.. 0.15 etc...

**Comment by harding** [comment]
@ocZio 0.14.0 through 0.16.2 can be found in https://bitcoincore.org/bin/insecure-CVE-2018-17144/ , which is labeled as "insecure" because those binaries are known to be vulnerable to being tricked into accepting invalid bitcoins or into being forced to shutdown remotely ("crash"), see https://bitcoincore.org/en/2018/09/20/notice/ for details.  You should not run those binaries in a production environment.

**Comment by ocZio** [comment]
Makes sense.

Thanks!
