### ISSUE TITLE
Remove misleading FAQ from website

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/bitcoincore.org#677]
Bitcoin Core is not an entity to provide technical or developer support, nor is it an entity to educate users about Bitcoin. While any Bitcoin Core contributor is free to do that in their personal or enterprise environment, the website seems the wrong place to put and maintain stuff like this https://bitcoincore.org/en/2016/06/08/version-bits-miners-faq/ and other faqs.

The website should only be used to provide downloads for Bitcoin Core and immediately related information about the software.

**Comment by MarcoFalke** [comment]
More so, highly political topics such as https://bitcoincore.org/en/2015/09/01/open-letter/ (which I have not signed btw ;) ) should also be removed.

**Comment by harding** [comment]
I'm weakly opposed to this removal.  I'm willing to agree that BitcoinCore.org may not be the best place for documentation about the Bitcoin system in general, but I don't think that means we should remove previously-published documentation or necessarily rule out future publication of general system documentation.

(The political stuff is a separate issue IMO.)

**Comment by MarcoFalke** [comment]
> rule out future publication of general system documentation.

I am not ruling out publication of documentation that is immediately related to Bitcoin Core. For example, we might want to host RPC documentation for each release of Bitcoin Core here.

**Comment by TheBlueMatt** [comment]
I don’t think this is sufficient reason to remove old, dated, content? If you’re worried about it sending the wrong signal we can make the date clearer or add some kind of text indicating the appropriate noice.

**Comment by harding** [comment]
FYI, we already do host RPC docs: https://bitcoincore.org/en/doc/

I just don't see any harm in hosting other documentation about the Bitcoin system, as long as it's something supported by Bitcoin Core (the software).  The BIP9 FAQ linked in your OP was a new and potentially confusing feature at the time of the BIP68/112/113 signaling period and I think publishing documentation about it made sense so that miners could learn how to signal in a way that Bitcoin Core would understand.

**Comment by laanwj** [comment]
Agree with @TheBlueMatt here.

Yes, it's old information, and new softforks are likely not to use BIP9. But I don't think that's enough reason to remove it from the site retroactively.

> FYI, we already do host RPC docs: https://bitcoincore.org/en/doc/

Hosting documentation is good. Specially user documentation is good. We should have more of it. 

Speaking of which, I'd like to move the bitcoin core doxygen documentation to bitcoincore.org at some point instead of dev.visucore.com.

**Comment by MarcoFalke** [comment]
> Speaking of which, I'd like to move the bitcoin core doxygen documentation to bitcoincore.org at some point instead of dev.visucore.com.

nice. ACK!

**Comment by MarcoFalke** [comment]
>     Speaking of which, I'd like to move the bitcoin core doxygen documentation to bitcoincore.org at some point instead of dev.visucore.com.


On a second thought this might not be such a good idea, because having doxygen run in a loop increases the attack surface on the server that hosts the binaries as well as the maintenance overhead. Some GitHub pages site on https://github.com/bitcoin-core/docs or so seems more appropriate.

**Comment by harding** [comment]
@MarcoFalke other options would be (1) a subdomain or (2) periodically updating the docs here using static files that go through the PR process like anything else.  Option 2 is how we currently do the RPC docs---we only update them once per major release (in a few minutes I'll be opening the PR for 0.19.0).

**Comment by MarcoFalke** [comment]
doxygen is for developer documentation, so should probably be updated every 12 hours for the master branch. Doing that with pull requests wouldn't work. See here for example on how it could be done with GitHub pages: https://github.com/achow101/bitcoin-docs-gen by @achow101

**Comment by harding** [comment]
A third alternative would be building the documentation on a $5/month vps (or one of our personal machines) and then rsyncing just the HTML to a dedicated sub-directory of the site using a restricted ssh key, e.g. https://www.guyrutenberg.com/2014/01/14/restricting-ssh-access-to-rsync/

Worst case would be that an attacker could mess with the doxygen documentation but not affect any other part of the site.

**Comment by TheBlueMatt** [comment]
This is actually how the site is built now and how the binaries are uploaded (separately). We could add another subdirectory, though that doesn’t negate the risk that that subdirectory holds its own “download links”.

**Comment by laanwj** [comment]
> On a second thought this might not be such a good idea, because having doxygen run in a loop increases the attack surface on the server that hosts the binaries as well as the maintenance overhead

FWIW, doxygen-in-a-loop already runs on an isolated account on a separate VM. The only thing that'd change is rsync'ing it to a different place.

**Comment by jnewbery** [comment]
Concept ACK using `docs.bitcoincore.org` for doxygen documentation. I have no opinion on implementation details.

**Comment by harding** [comment]
There's a slight (alleged) SEO benefit to putting it on the main domain rather than a subdomain due to links to the main site pages increasing the page rank of the doxygen pages and vice-versa.  That's probably pretty minor though.

I don't think there's any real risk difference related to rouge download links between using a subdomain and putting pages on the main site: an attack could probably be just as effective using `docs.bitcoincore.org/download` as it would be using `bitcoincore.org/docs/download`.

Concept ACK from me for either a subdomain or pushing the content to the main site in a directory separate from the rest of the content, e.g. `/docs/doxygen/`
