### ISSUE TITLE
SSL ceritifcate expired, gives browser warning

### ISSUE THREAD

**Issue by Stadicus** [bitcoin-core/bitcoincore.org#690]
The Let's Encrypt SSL certificate for https://bitcoincore.org expired today at 7:56 CET.

![Screenshot from 2019-11-28 09-17-52](https://user-images.githubusercontent.com/19550140/69789155-43f8e700-11c0-11ea-8923-a38caa7669b1.png)

**Comment by TheBlueMatt** [comment]
Ugh. I get to wear the dunce cap on this one. Looks like certbot changed their reminder frequency and I let the date pass. I'll figure out some scripts to auto-renew while still avoiding certbot on the actual webhost.

**Comment by Sjors** [comment]
You don't like random scripts with root access? :-)

**Comment by cereal7802** [comment]
> Ugh. I get to wear the dunce cap on this one. Looks like certbot changed their reminder frequency and I let the date pass. I'll figure out some scripts to auto-renew while still avoiding certbot on the actual webhost.

Have you considered acme.sh? It is possible to run the script to generate the certs instead of certbot. Works pretty well and has a decent number of options for deploying the generated certs.

**Comment by Stadicus** [comment]
Thanks for fixing, works like a charm again. Issue can be closed, unless you want to track some follow-up work.

**Comment by TheBlueMatt** [comment]
This was my fault. Apparently letsencrypt changed their email notifications so this refresh was missed. Of course we’re not gonna run a large python program like certbot on the server serving binaries, which makes this somewhat more complicated. 

Luckily we recently started hosting DNS ourselves so we can run certbot in DNS mode on a separate machine. That’s done now (which is why it took a while to renew this morning), so hopefully this will not be an issue in the future, though I need to finish fully automating it today.

As for acme.sh, last I checked it was also a rather large codebase to audit, plus shell scripts downloading things is also pretty scary. In any case, DNS remotely is good.

**Comment by qertoip** [comment]
Why not buy a commercial certificate for 2 years and be done with all the complexity?

Let's Encrypt and its auto renewal mechanism are known to be flaky. Renewal is not guaranteed, there are often technical glitches.

(I can happily cover the costs if necessary)

**Comment by TheBlueMatt** [comment]
I’ve never headed of letsencrypt being flaky in the automated renewal, and certainly having a shorter validity time is good security practice.

**Comment by laanwj** [comment]
Thanks for offering anyway!

I'm going to close this topic, there's no immediate problem anymore.
