### ISSUE TITLE
Signature verification instructions needs updating.

### ISSUE THREAD

**Issue by spinza** [bitcoin-core/bitcoincore.org#793]
On this page: 
https://bitcoincore.org/en/download/

The signature verification instructions need to be fixed for 0.22 as they are different as the files are split.

**Comment by prayank23** [comment]
@spinza Version is ~~0.22~~ 22.0

**Comment by meeDamian** [comment]
Anyone trying to verify see: https://github.com/lncm/docker-bitcoind/pull/59#issuecomment-918908987

**Comment by laanwj** [comment]
Correct. Besides using detached signing, there is no longer a single distribution signing key, but signatures that are created as part of the build attestation process. Here, the signatures of individual builders are packaged.

There's some information about the new verification process here: https://github.com/bitcoin/bitcoin/issues/22634

[These instructions](https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys) help if you want to download all the potential signer keys. You could get all of them, or a subset, it's really up to you who you trust to do a bitcoin core release.

**Comment by meeDamian** [comment]
I must say, I personally **really** appreciate this change.

> You could get all of them, or a subset, it's really up to you who you trust to do a bitcoin core release.

How to verify using only some keys? For me, `gpg` errors any time I'm missing a key.

**Comment by Fonta1n3** [comment]
When I run `gpg --verify SHA256SUMS.asc SHA256SUMS` gpg has to be force quit and it seems @laanwj signature is not present. I have a Bitcoin Core installer which programmatically checks the sigs but this issue with gpg just hanging breaks it.

Is your sig missing intentionally @laanwj? See my gpg output:

```
gpg: Signature made Fri Sep 10 19:29:17 2021 WITA
gpg:                using RSA key 0CCBAAFD76A2ECE2CCD3141DE2FFD5B1D88CA97D
gpg: Good signature from ".0xB10C <0xb10c@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 982A 193E 3CE0 EED5 35E0  9023 188C BB26 4841 6AD5
     Subkey fingerprint: 0CCB AAFD 76A2 ECE2 CCD3  141D E2FF D5B1 D88C A97D
gpg: Signature made Fri Sep 10 04:09:04 2021 WITA
gpg:                using RSA key 152812300785C96444D3334D17565732E08E5E41
gpg:                issuer "achow101@gmail.com"
gpg: Good signature from "Andrew Chow (Official New Key) <achow101@gmail.com>" [unknown]
gpg:                 aka "Andrew Chow <achow101-github@achow101.com>" [unknown]
gpg:                 aka "Andrew Chow <achow101-lists@achow101.com>" [unknown]
gpg:                 aka "Andrew Chow <achow101@pm.me>" [unknown]
gpg:                 aka "Andrew Chow <achow101@protonmail.com>" [unknown]
gpg:                 aka "Andrew Chow <achow101@yahoo.com>" [unknown]
gpg:                 aka "Andrew Chow <andrew@achow101.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1528 1230 0785 C964 44D3  334D 1756 5732 E08E 5E41
gpg: Signature made Fri Sep 10 04:16:18 2021 WITA
gpg:                using RSA key 0AD83877C1F0CD1EE9BD660AD7CC770B81FD22A8
gpg:                issuer "benthecarman@live.com"
gpg: Good signature from "Ben Carman <benthecarman@live.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0AD8 3877 C1F0 CD1E E9BD  660A D7CC 770B 81FD 22A8
gpg: Signature made Fri Sep 10 21:00:35 2021 WITA
gpg:                using RSA key 590B7292695AFFA5B672CBB2E13FC145CD3F4304
gpg:                issuer "darosior@protonmail.com"
gpg: Good signature from "Antoine Poinsot <darosior@protonmail.com>" [unknown]
gpg:                 aka "darosior <darosior@protonmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 590B 7292 695A FFA5 B672  CBB2 E13F C145 CD3F 4304
gpg: Signature made Fri Sep 10 04:54:01 2021 WITA
gpg:                using RSA key 28F5900B1BB5D1A4B6B6D1A9ED357015286A333D
gpg: Good signature from "Duncan Dean <duncangleeddean@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9484 44FC E03B 05BA 5AB0  591E C37B 1C1D 44C7 86EE
     Subkey fingerprint: 28F5 900B 1BB5 D1A4 B6B6  D1A9 ED35 7015 286A 333D
gpg: Signature made Fri Sep 10 22:26:03 2021 WITA
gpg:                using RSA key 637DB1E23370F84AFF88CCE03152347D07DA627C
gpg: Good signature from "Stephan Oeste (it) <it@oeste.de>" [unknown]
gpg:                 aka "Emzy E. (emzy) <emzy@emzy.de>" [unknown]
gpg:                 aka "Stephan Oeste (Master-key) <stephan@oeste.de>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9EDA FF80 E080 6596 04F4  A76B 2EBB 056F D847 F8A7
     Subkey fingerprint: 637D B1E2 3370 F84A FF88  CCE0 3152 347D 07DA 627C
gpg: Signature made Fri Sep 10 09:04:14 2021 WITA
gpg:                using RSA key CFB16E21C950F67FA95E558F2EEB9F5CC09526C1
gpg:                issuer "fanquake@gmail.com"
gpg: Good signature from "Michael Ford (bitcoin-otc) <fanquake@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E777 299F C265 DD04 7930  70EB 944D 35F9 AC3D B76A
     Subkey fingerprint: CFB1 6E21 C950 F67F A95E  558F 2EEB 9F5C C095 26C1
gpg: Signature made Fri Sep 10 16:03:16 2021 WITA
gpg:                using RSA key 6E01EEC9656903B0542B8F1003DB6322267C373B
gpg:                issuer "gugger@gmail.com"
gpg: Good signature from "Oliver Gugger <gugger@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F4FC 70F0 7310 0284 24EF  C20A 8E42 5659 3F17 7720
     Subkey fingerprint: 6E01 EEC9 6569 03B0 542B  8F10 03DB 6322 267C 373B
gpg: Signature made Fri Sep 10 04:07:53 2021 WITA
gpg:                using RSA key D1DBF2C4B96F2DEBF4C16654410108112E7EA81F
gpg:                issuer "hebasto@gmail.com"
gpg: Good signature from "Hennadii Stepanov (hebasto) <hebasto@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D1DB F2C4 B96F 2DEB F4C1  6654 4101 0811 2E7E A81F
gpg: Signature made Fri Sep 10 15:14:14 2021 WITA
gpg:                using RSA key 82921A4B88FD454B7EB8CE3C796C4109063D4EAF
gpg:                issuer "jon@atack.com"
^C
gpg: signal Interrupt caught ... exiting
```

**Comment by luckman212** [comment]
Can some kind soul please post a list of steps to properly verify the 22.0 release hashes? I have 7 Chrome tabs open now, have just imported 54 untrusted keys from https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys and am still scratching my head. This seems important. Why not have some clear instructions?

The key below seems to belong to `.0xB10C <0xb10c@gmail.com>`
Can't find mention of this anywhere ... ?

![CleanShot 2021-09-15 at 23 18 14](https://user-images.githubusercontent.com/1992842/133543901-3e442278-af5c-427d-8ffb-f5524c333388.png)

**Comment by dongcarl** [comment]
@luckman212 I think gpg's user interface is a bit confusing in this case for combined signature files, because it leads you to think that you need to verify EVERYONE's signature in order to have some trust in the binary, when in reality, if you don't have someone's key and you don't know how to get it from them, their signature doesn't impact your trust in the binary that much.

That being said, you are right that we should make sure we have keys for everyone that uploads to guix.sigs. I've opened https://github.com/bitcoin-core/guix.sigs/issues/133 for this issue.

As for your specific problem of finding b10c's keys, I was able to find it here on his website: https://b10c.me/gpg.txt
I personally ran into trouble finding sipsorcery's key, which is available here: https://github.com/sipsorcery.gpg

**Comment by dongcarl** [comment]
If someone knows a GPG option that's like `--verify-but-for-multiple-packets-only-error-out-if-no-signatures-below-certain-trust-level`, that'd be great 😆

**Comment by jamesob** [comment]
> Can some kind soul please post a list of steps to properly verify the 22.0 release hashes? I have 7 Chrome tabs open now, have just imported 54 untrusted keys from https://github.com/bitcoin/bitcoin/tree/master/contrib/builder-keys and am still scratching my head. 

@luckman212 sorry you had to go through such a laborious process to obtain the builder keys. You can automate builder key retrieval to some extent by running the following in your shell (instead of having to manually download each developer's key):

```python
% python3 -c'
import urllib.request
import subprocess

for line in urllib.request.urlopen("https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt").readlines():
  key, name = line.decode().strip().split(" ", 1)
  if input(f"Retrieve key {key} for {name}? (y/N) ").lower() == "y":
    subprocess.run(f"gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys {key}", shell=True)
'
```

Be sure to inspect each entry manually to ensure https fidelity.

(Amusingly I tried in vain to do this in pure, cross-platform bash for about 30 minutes, then it took me maybe 3 minutes to write this Python after declaring bankruptcy.)

**Comment by TheBlueMatt** [comment]
> for line in urllib.request.urlopen("https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt").readlines():

Eek, lets not rely on just fetching a keys list from github. Ideally we'd publish the set of key fingerprints broadly, ensure the keys are signed with the previous release signing key (I don't believe any of them are?) and also make sure a verification script can handle the signing keys rotating a key or two at a time across releases, using the previous keys as the signing set (and allowing a few missing keys).

**Comment by jamesob** [comment]
> Eek, lets not rely on just fetching a keys list from github.

I'm with you but right now what people are doing is staring at the Github UI and manually retrieving keys, so we should at least make that easier. I'd love to do what you're describing but it's a big process change.

**Comment by ParkaMark** [comment]
I must say, this has been one of the most PITA changes I've had to deal with, with regards to automating the polling, verification and then download and installation of bitcoind - but the script below now achieves what I wanted.

Note I had to use some prime number version construction in order to make the version string "22.0" (which is how this new version has been released on the website) to equal the version string "22.0.0" which is how the version is reported when running "bitcoind -version" on the command line. The version function effectively resolves both of these strings to the same unique number where I can then test for equality.

They gpg keys issue still looks very flakey - I managed to import all the necessary keys manually outside of this script from various sources/posts located elsewhere, but the verification now works as expected.

So posting the below incase anyone finds this useful.

```
#!/bin/bash

version() {
  cat | awk -F . '{print 2^$1 * 3^$2 * 5^$3 * 7^$4}'
}

latest=$(curl -s https://bitcoincore.org/en/download/ | egrep -o 'Latest version: [0-9.]+' | awk '{print $NF}')
[[ -z $latest ]] && exit 1
[[ $(~/bin/bitcoind -version | head -1 | egrep -o '[0-9.]+' | version) -eq $(echo $latest | version) ]] && exit 0

for x in SHA256SUMS{,.asc}
do
  wget -qN https://bitcoincore.org/bin/bitcoin-core-${latest}/${x}
done

gpg --verify SHA256SUMS.asc SHA256SUMS && \
wget -q https://bitcoincore.org/bin/bitcoin-core-${latest}/bitcoin-${latest}-x86_64-linux-gnu.tar.gz && \
sha256sum --ignore-missing --check SHA256SUMS && \
tar zxvf bitcoin-${latest}-x86_64-linux-gnu.tar.gz && \
rm -vrf bin && \
mv -v bitcoin-*/bin . && \
rm -vrf bitcoin-* && \
/script/to/restart/bitcoind
```

**Comment by 1ddV** [comment]
Isn't it enough to validate the binary with only 1 trusted signature? I have for instance only Wladimir J. van der Laan's certified key and I get a good signature with his key:

[...]
gpg: Signature made 09/10/21 09:14:14 Romance Daylight Time
gpg:                using RSA key 82921A4B88FD454B7EB8CE3C796C4109063D4EAF
gpg:                issuer "jon@atack.com"
gpg: Can't check signature: No public key
gpg: Signature made 09/10/21 19:33:30 Romance Daylight Time
gpg:                using RSA key 9DEAE0DC7063249FB05474681E4AED62986CD25D
**_gpg: Good signature from "Wladimir J. van der Laan <laanwj@visucore.com>" [full]
gpg:                 aka "Wladimir J. van der Laan <laanwj@gmail.com>" [full]
gpg:                 aka "Wladimir J. van der Laan <laanwj@protonmail.com>" [full]_**
[...]

**Comment by 1ddV** [comment]
Thanks @jamesob !

**Comment by diegoviola** [comment]
> Isn't it enough to validate the binary with only 1 trusted signature?

This is what I did and I think it's good enough for me.

**Comment by luckman212** [comment]
> _I tried in vain to do this in pure, cross-platform bash_

@jamesob Thanks for the python script. I created a Bash version too—not sure if anyone finds it useful.

```bash
#!/usr/bin/env bash

curlopts=( --silent --fail --max-time 10 --stderr /dev/null )
keyfile='https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/builder-keys/keys.txt'
pubring='pubring.kbx' #may be trustedkeys.kbx on some systems

if [ ! -e SHA256SUMS ] || [ ! -e SHA256SUMS.asc ]; then
  echo "missing SHA256SUMS/SHA256SUMS.asc files"
  echo "download from https://bitcoincore.org/en/download/"
  exit 1
fi

if ! keys=$(curl "${curlopts[@]}" $keyfile); then
  echo 'error fetching keys from github'
  exit 1
fi

while read -r KEY NAME; do
  if ! gpg --list-key "$KEY" &>/dev/null; then
    echo "trying to import $KEY $NAME"
    if ! gpg --keyserver hkps://keys.openpgp.org --recv-keys "$KEY" &>/dev/null; then
      gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "$KEY" &>/dev/null
    fi
  fi
done <<<"$keys"

#clean up expired keys
while read -r KEY; do
  echo "deleting expired key $KEY"
  gpg --batch --yes --delete-keys "$KEY" &>/dev/null
done < <(gpg --list-keys --with-colons | awk -F: '$1=="pub" && $2~"[er]" { print $5 }')

goodsigs=$(gpgv --keyring $pubring --quiet SHA256SUMS.asc SHA256SUMS 2>&1 | grep -c '^gpgv: Good signature')
if (( goodsigs > 0 )); then
  echo "SHA256SUMS passed verification (found $goodsigs good signatures)"
  sha256sum -c --ignore-missing <SHA256SUMS
else
  echo "SHA256SUMS did not pass verification!"
fi
```

**Comment by laanwj** [comment]
> Isn't it enough to validate the binary with only 1 trusted signature?

That's something you decide for yourself. Future releases may not always be signed by me, though.

**Comment by iprok** [comment]
@laanwj hello! Excuse me, but, as for me, it seems to be very irresponsible of bitcoin core team. Being ordinal bitcoin core user, I'm updating it by visiting https://bitcoin.org/ru/download . 
For the current moment I can see three links that relate to me there:
1) Download link, e.g. https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-x86_64-linux-gnu.tar.gz
2) [Verify release signatures](https://bitcoin.org/bin/bitcoin-core-22.0/SHA256SUMS.asc). I assumed (basing on previous updates) that I can download file with checksums from the link.
3) Bitcoin core Bitcoin Core Release Signing Keys ([v0.11.0+](https://bitcoin.org/laanwj-releases.asc)). I assumed that I should use it to check signatures of releases. 

And of course I'm failing doing this. Because before finding that thread https://bitcoin.org/bin/bitcoin-core-22.0/SHA256SUMS.asc looked for me as list of unknown signatures of strangers without any checksums. 
And even after small investigation and visiting https://bitcoin.org/bin/bitcoin-core-22.0/, finding https://bitcoin.org/bin/bitcoin-core-22.0/SHA256SUMS I wasn't able to check it because I see no valid signatures at
https://bitcoin.org/bin/bitcoin-core-22.0/
nor at
https://bitcoin.org/ru/download
nor any actual instructions to the things that have changed.

My first thought was that site with such business critical software like bitcoin core was hacked and I must not trust it.

Please make contents of your download pages actual.

**Comment by MarcoFalke** [comment]
This is the issue tracker for `bitocincore.org`, not `bitcoin.org`. You can find the download page and steps to verify here: https://bitcoincore.org/en/download/#verify-your-download
